packages:
  - HDBC-session/
  - names-th/
  - persistable-record/
  - persistable-types-HDBC-pg/
  - relational-query/
  - relational-query-HDBC/
  - relational-record/
  - relational-schemas/
  - sql-words/
  - text-postgresql/

#  - relational-record-examples/
#  - examples/HDBC/MySQL/
#  - examples/HDBC/Oracle/
#  - examples/HDBC/PostgreSQL

extra-deps:
#  - HDBC-mysql-0.6.6.1
#  - HDBC-odbc-2.4.0.1
#  - HDBC-postgresql-2.3.2.3
#  - HDBC-sqlite3-2.3.3.1
  - quickcheck-simple-0.1.0.0
resolver: nightly-2016-10-10
